const mediaConf = {
  MEDIA_WIDTH_MIN: `calc(414px + 1px)`,
  MEDIA_WIDTH_MAX: `9999px`,

  MEDIA_WIDTH_MOBILE_MIN: `0px`,
  MEDIA_WIDTH_MOBILE_MAX: `calc(516px - 1px)`,

  MEDIA_WIDTH_TABLET_MIN: `calc(516px - 1px)`,
  MEDIA_WIDTH_TABLET_MAX: `calc(1025px - 1px)`,

  MEDIA_WIDTH_DESKTOP: `calc(1025px - 1px)`,
  MEDIA_WIDTH_DESKTOP_MAX: `9999px`,

  MEDIA_HEIGHT_DESKTOP: `calc(1020px - 1px)`,
  MEDIA_HEIGHT_DESKTOP_MAX: `1366px`,

  MEDIA_WIDTH_DESKTOP_CONTENT: `1600px`,
  MEDIA_HEIGHT_DESKTOP_CONTENT: `1280px`,
  MEDIA_WIDTH_DESKTOP_CONTENT_PADDING: `6%`,

  MEDIA_WIDTH_MOBILE_CONTENT: `calc(414px + 1px)`,
  MEDIA_WIDTH_MOBILE_CONTENT_PADDING: `6%`,

  MEDIA_WIDTH_16_9_ASPECT: `calc(100vw * 0.5625)`,
  LAYOUT_DEFAULT_Z_INDEX: `999`,
  COMPONENT_DEFAULT_Z_INDEX: `100`,
};

export default mediaConf;
